name: Build & Test gonedrive

on: [push, pull_request]

jobs:
  test:
    name: Test Go ${{ matrix.go }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        go: [ '1.13', '1.12' ]
        platform: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: make install

    - name: Build
      run: make build

    - name: Vet the code
      run: make vet

    - name: Run unit tests
      run: make test

  update-doc:
    needs: test
    name: Update the documentation when new commands are implemented
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - uses: actions/checkout@v2

    - name: Update documentation with doc/doc_generator.go
      run: make doc

    - uses: EndBug/add-and-commit@v2
      with:
        author_name: Doc Bot
        author_email: docbot@gonedrive.com
        message: "Update command documentation"
        pattern: "*.md"
        path: "./doc"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
